SET C51INC=D:\programfiles-install\keilMDK523\C51\Inc;D:\programfiles-install\keilMDK523\C51\Inc\STC
SET C51LIB=D:\programfiles-install\keilMDK523\C51\Lib
SET CPU_TYPE=STC89C52RC
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02AEA540
"D:\programfiles-install\keilMDK523\C51\BIN\C51.EXE" @".\out\main.__i"
"D:\programfiles-install\keilMDK523\C51\BIN\C51.EXE" @".\out\tcs.__i"
"D:\programfiles-install\keilMDK523\C51\BIN\C51.EXE" @".\out\pwm.__i"
"D:\programfiles-install\keilMDK523\C51\BIN\BL51.EXE" @".\out\music.lnp"
"D:\programfiles-install\keilMDK523\C51\BIN\OH51.EXE" ".\out\music" 
